apiVersion: v1
kind: Service
metadata:
  name: external-lb
  namespace: petclinic
spec:
  selector:
    tier: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-svc
  type: LoadBalancer
