apiVersion: v1
kind: Service
metadata:
  name: internal-lb
spec:
  selector:
    tier: was
  ports:
    - name: ajp
      protocol: TCP
      port: 8009
      targetPort: ajp
    
    - name: tomcat
      protocol: TCP
      port: 8080
      targetPort: petclinic-svc
  clusterIP: 10.111.254.254
