apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: web
    tier: frontend
    release: stable
  name: webui
spec:
  nodeSelector:
    diskType: ssd
  containers:
  - image: nginx:1.14
    name: nginx
    command: ["/bin/bash"]
    #    args: ["-c", "sleep 10000"]
    #    args: ["echo 'Helping You Adopt Cloud' > /usr/share/nginx/html/index.html"]
    args: ["-c","while true; do echo 'Helping You Adopt Cloud' > /usr/share/nginx/html/index.html; service nginx start; done;"]
    ports:
    - containerPort: 80
    resources: 
      limits:
        memory: 700Mi
        cpu: 500m
