apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: web
    tier: frontend
    release: stable
  name: webui
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  nodeSelector:
    diskType: ssd
  containers:
  - image: nginx:1.14
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
    name: nginx
    #    command: ["/bin/bash"]
    #    args: ["-c", "sleep 10000"]
    #    args: ["echo 'Helping You Adopt Cloud' > /usr/share/nginx/html/index.html"]
    ports:
    - containerPort: 80
    resources: 
      limits:
        memory: 700Mi
        cpu: 500m
  - image: busybox
    name: busy-box
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
      command: ["/bin/sh"]
      args: ["echo 'Helping You Adopt Cloud' > /pod-data/index.html"]
