apiVersion: v1
kind: Pod
metadata:
  name: genid-args
spec:
  containers:
  - image: smlinux/genid:args
    env:
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
          name: class1-config
          key: interval
    args: ["$INTERVAL"]
    name: faceid-generator
    volumeMounts:
    - name: html
      mountPath: /webdata
  - image: nginx:1.14
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
  volumes:
  - name: html
    emptyDir: {}
