apiVersion: v1
kind: LimitRange
metadata:
  name: limit-example
  namespace: devops
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 100m
      memory: 10Mi
    default:
      cpu: 200m
      memory: 100Mi
    min:
      cpu: 100m
      memory: 10Mi
    max:
      cpu: 1
      memory: 1Gi
    maxLimitRequestRatio:
      cpu: 4
      memory: 10

  - type: Pod
    min:
      cpu: 100m
      memory: 10Mi
    max:
      cpu: 1
      memory: 1Gi

  - type: PersistentVolumeClaim    
    min:
      storage: 1Gi
    max:
      storage: 10Gi
