apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-appjs

spec:
  replicas: 3
  selector:
      app: appjs
  template:
    metadata:
      labels:
        app: appjs
    spec:
      containers:
        - image: smlinux/appjs
          name: appjs-container
          ports:
            - containerPort: 8080
          readinessProbe:
            exec:
              command:
                - ls
                - /var/ready
            initialDelaySeconds: 60
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 1
