apiVersion: v1
kind: ReplicationController
metadata:
  name: lab-readiness
spec:
  replicas: 3
  selector:
    app: web
  template:
    metadata:
      name: readiness-pod
      labels:
        app: web
    spec:
      containers:
      - image: nginx:1.14
        name: nginx
        ports:
        - containerPort: 80
        readinessProbe:
          exec:
            command:
            - ls
            - /var/ready
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 1
