apiVersion: v1
kind: Pod
metadata:
  name: appjs-pod-ann
  annotations:
    imageregistry: "https://hub.docker.com/"
    description: "Simple appjs-nased Web Server"
spec:
  containers:
  - name: appjs-container
    image: smlinux/appjs
    ports:
    - containerPort: 8080
