apiVersion: v1
kind: Pod
metadata:
  name: nginx-readiness
spec:
  containers:
  - image: nginx:1.14
    name: nginx
    ports:
    - containerPort: 80
    readinessProbe:
      exec:
        command:
        - ls
        - /var/datafile 
