apiVersion: v1
kind: Service
metadata:
  name: svc-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appjs
  template:
    metadata:
      labels:
        app: appjs
    spec:
      type: NodePort
      nodePort: 8080
      containers:
      - name: appjs-container
        image: smlinux/appjs
        ports:
        - containerPort: 8080
